modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)" #mandatory (28 is current forge version)
[[mods]] #mandatory
modId="deathquotes" #mandatory
version="${file.jarVersion}" #mandatory
displayName="DeathQuotes" #mandatory
logoFile="deathquotes.png" #optional
authors="Cazsius" #optional
description='''Adding Unique, Customizable quotes when a player dies! '''


